from fastapi import APIRouter

from app.api import audio_upload, voice_signaling_ws, voice_ws
from app.api.endpoints import (
    admin_play_applications,
    admin_users,
    auth,
    chat,
    custom_games,
    play_applications,
    research,
    rooms,
    stats,
    users,
    voice,
    webrtc,
)


api_router = APIRouter()

api_router.include_router(
    auth.router,
    prefix="/auth",
    tags=["authentication"],
)
api_router.include_router(
    users.router,
    prefix="/users",
    tags=["users"],
)
api_router.include_router(
    rooms.router,
    prefix="/rooms",
    tags=["rooms"],
)
api_router.include_router(
    voice.router,
    prefix="/voice",
    tags=["voice"],
)
api_router.include_router(
    voice_ws.router,
    prefix="/ws",
    tags=["voice_ws"],
)
api_router.include_router(
    voice_signaling_ws.router,
    tags=["voice_signaling_ws"],
)
api_router.include_router(
    audio_upload.router,
    tags=["audio_upload"],
)
api_router.include_router(
    stats.router,
    prefix="/stats",
    tags=["stats"],
)
api_router.include_router(
    custom_games.router,
    prefix="",
    tags=["custom_games"],
)
api_router.include_router(
    chat.router,
    prefix="",
    tags=["chatbot"],
)
api_router.include_router(
    research.router,
    prefix="/research",
    tags=["research"],
)
api_router.include_router(
    webrtc.router,
    prefix="/webrtc",
    tags=["webrtc"],
)
api_router.include_router(
    play_applications.router,
    prefix="/play-applications",
    tags=["play_applications"],
)
api_router.include_router(
    admin_play_applications.router,
    prefix="/admin/play-applications",
    tags=["admin_play_applications"],
)
api_router.include_router(
    admin_users.router,
    prefix="/admin/users",
    tags=["admin_users"],
)