"""create custom_games

Revision ID: 1835a67cf28d
Revises: 76aded6f6365
Create Date: 2025-09-06 23:51:46.600586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1835a67cf28d'
down_revision: Union[str, None] = '76aded6f6365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('teacher_name', sa.String(length=100), nullable=False),
    sa.Column('teacher_school', sa.String(length=200), nullable=False),
    sa.Column('teacher_email', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('representative_image_url', sa.String(length=500), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_custom_game_code')
    )
    op.create_index(op.f('ix_custom_games_code'), 'custom_games', ['code'], unique=True)
    op.create_index(op.f('ix_custom_games_id'), 'custom_games', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_games_id'), table_name='custom_games')
    op.drop_index(op.f('ix_custom_games_code'), table_name='custom_games')
    op.drop_table('custom_games')
    # ### end Alembic commands ###
