"""add play approval system

Revision ID: 33c5c4bdb54e
Revises: a1b2c3d4e5f6
Create Date: 2026-08-30 04:10:34.953049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c5c4bdb54e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_applications_id'), 'play_applications', ['id'], unique=False)
    op.create_index(op.f('ix_play_applications_user_id'), 'play_applications', ['user_id'], unique=True)
    op.add_column(
    'users',
    sa.Column(
        'is_admin',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_play_applications_user_id'), table_name='play_applications')
    op.drop_index(op.f('ix_play_applications_id'), table_name='play_applications')
    op.drop_table('play_applications')
    # ### end Alembic commands ###
