"""add role_id to room_participants

Revision ID: 3e11c7e5654f
Revises: 661c490addfe
Create Date: 2025-07-08 13:54:09.019451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e11c7e5654f'
down_revision: Union[str, None] = '661c490addfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_participants', sa.Column('role_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_participants', 'role_id')
    # ### end Alembic commands ###
