"""Increase room_code length from 8 to 20 characters

Revision ID: 67a0cbae1d20
Revises: 8fdd9b006674
Create Date: 2025-05-26 15:08:47.671075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67a0cbae1d20'
down_revision: Union[str, None] = '8fdd9b006674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'room_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'room_code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
