"""make_created_by_nullable_for_guests

Revision ID: 76aded6f6365
Revises: 5c643d20447c
Create Date: 2025-08-21 00:47:42.688047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76aded6f6365'
down_revision: Union[str, None] = '5c643d20447c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Make created_by column nullable for guest users
    op.alter_column('rooms', 'created_by',
                    existing_type=sa.Integer(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Make created_by column not nullable again
    op.alter_column('rooms', 'created_by',
                    existing_type=sa.Integer(),
                    nullable=False)
    # ### end Alembic commands ###
