"""Add allow_random_matching field to rooms and set max_players to 3

Revision ID: 8fdd9b006674
Revises: 3d628f15fa68
Create Date: 2025-05-26 13:35:29.039608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fdd9b006674'
down_revision: Union[str, None] = '3d628f15fa68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('allow_random_matching', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'allow_random_matching')
    # ### end Alembic commands ###
