"""Add voice chat tables

Revision ID: 92d3cafd34d8
Revises: a1daa9796144
Create Date: 2025-06-23 14:15:55.985210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92d3cafd34d8'
down_revision: Union[str, None] = 'a1daa9796144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_sessions_id'), 'voice_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_session_id'), 'voice_sessions', ['session_id'], unique=True)
    op.create_table('voice_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('is_mic_on', sa.Boolean(), nullable=False),
    sa.Column('is_speaking', sa.Boolean(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('recording_file_path', sa.String(length=255), nullable=True),
    sa.Column('recording_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recording_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_participants_id'), 'voice_participants', ['id'], unique=False)
    op.create_table('voice_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_recordings_id'), 'voice_recordings', ['id'], unique=False)
    op.alter_column('users', 'birthdate',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthdate',
               existing_type=sa.String(length=7),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_voice_recordings_id'), table_name='voice_recordings')
    op.drop_table('voice_recordings')
    op.drop_index(op.f('ix_voice_participants_id'), table_name='voice_participants')
    op.drop_table('voice_participants')
    op.drop_index(op.f('ix_voice_sessions_session_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_id'), table_name='voice_sessions')
    op.drop_table('voice_sessions')
    # ### end Alembic commands ###
