"""Add is_host field to room_participants table

Revision ID: a1daa9796144
Revises: 26eee00c953f
Create Date: 2025-06-11 20:49:35.623317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1daa9796144'
down_revision: Union[str, None] = '26eee00c953f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_participants', sa.Column('is_host', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_participants', 'is_host')
    # ### end Alembic commands ###
