"""add confidence fields to round and consensus choices

Revision ID: bbb9cc51224e
Revises: f661ecf3115a
Create Date: 2025-07-12 16:33:08.942366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb9cc51224e'
down_revision: Union[str, None] = 'f661ecf3115a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consensus_choices', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('round_choices', sa.Column('confidence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('round_choices', 'confidence')
    op.drop_column('consensus_choices', 'confidence')
    # ### end Alembic commands ###
