name: Deploy AI Ethics Game Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "[1] 프로젝트 위치 이동 또는 클론"
            cd ~
            if [ -d "ai_ethics_game" ]; then
              cd ai_ethics_game
              git pull origin main
            else
              git clone https://github.com/${{ github.repository }}.git ai_ethics_game
              cd ai_ethics_game
            fi

            echo "[2] .env 파일 생성"
            cat > .env << EOF
            ${{ secrets.ENV_VARS }}
            BACKEND_CORS_ORIGINS=["http://localhost:3000", "http://localhost:8000"]
            EOF

            echo "[3] 도커 리셋 및 빌드"
            docker-compose down || true
            docker system prune -af
            docker-compose up -d --build

            echo "[4] 헬스 체크"
            sleep 10
            curl -f http://localhost:8000/health || exit 1

            echo "✅ Deployment Completed Successfully!"