name: Deploy AI Ethics Game Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        DATABASE_URL: mysql+aiomysql://test_user:test_password@localhost:3306/test_db
        SECRET_KEY: test-secret-key
      run: |
        python -m pytest tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "[1] 프로젝트 위치 이동 또는 클론"
          cd ~
          if [ -d "ai_ethics_game" ]; then
            cd ai_ethics_game
            git pull origin main
            cd ..
          else
            git clone https://github.com/${{ github.repository }}.git ai_ethics_game
          fi
          cd ai_ethics_game

          echo "[2] .env 파일 생성"
          echo "${{ secrets.ENV_VARS }}" > .env

          echo "[3] 도커 리셋 및 빌드"
          docker-compose down || true
          docker system prune -af

          echo "[4] 도커 실행"
          docker-compose up -d --build

          echo "[5] 헬스 체크"
          sleep 20
          curl -f http://localhost:8000/health || exit 1

          echo "✅ 배포 완료!"
